[workspace]
members = ["bin", "lib"]
resolver = "2"

[workspace.dependencies]
opentelemetry = "0.18"
opentelemetry_api = {version="0.18", default-features = false, features=["trace"]}
opentelemetry_sdk = "0.18"
